[package]
name = "bfs"
version = "0.1.0"
authors = ["Brett Fazio, Ellie Kozlowski, Dylan Ochoa, Blake Robertson, Idel Martinez"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.1"
grid = "*"